action.yml
src/publish-docker.ts
src/utils/docker.ts
test/publish-docker.spec.ts
test/utils/docker.spec.ts

Falls back to latest by default

feat: allow publishing multiple tags

---

renovate.json

* automerge minor dev deps
* group prettier packages

chore(renovate): reconfigure

---

.github/workflows/build.yml
builder.json
e2e/node.json
e2e/yarn.json
src/commands/docker/builder.ts
test/commands/docker/__fixtures__/dummy.json
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts

* allow override `latestVersion`
* extend e2e tests

feat(docker-builder): simplify usage

---

Dockerfile
e2e/yarn.json
renovate.json
src/commands/docker/builder.ts
src/util.ts
test/__snapshots__/util.spec.ts.snap
test/commands/docker/__fixtures__/pnpm.json
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts
test/util.spec.ts

feat(docker-builder): grep config from dockerfile

---

action.yml
src/commands/docker/builder.ts
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts

feat(docker-builder): optimize tagging

---

src/commands/docker/builder.ts
src/utils/docker.ts
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/utils/__snapshots__/docker.spec.ts.snap
test/utils/docker.spec.ts

fix: wrong build arg version

---

.github/workflows/build.yml
e2e/renovate.json
package.json
src/commands/docker/builder.ts
src/utils/datasource/index.ts
src/utils/datasource/renovate-slim.ts
test/__snapshots__/util.spec.ts.snap
test/commands/docker/__fixtures__/dummy.json
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts
test/utils/datasource/index.spec.ts
test/utils/datasource/renovate-slim.spec.ts
yarn.lock

* feat: add renovate datasource
* fix: filter unstable versions correctly

feat: add renovate datasource

---

Dockerfile
src/utils/datasource/renovate-slim.ts
test/__snapshots__/util.spec.ts.snap
test/utils/datasource/renovate-slim.spec.ts

Reverts renovatebot/internal-tools#59

fix(docker-builder): revert fetch latest slim version from dockerfile

---

Dockerfile
src/utils/datasource/renovate-slim.ts
test/__snapshots__/util.spec.ts.snap
test/utils/datasource/renovate-slim.spec.ts

Reverts renovatebot/internal-tools#60

fix(docker-builder): revert revert fetch latest slim version from dockerfile

---

.eslintrc.js
package.json
src/commands/docker/builder.ts
src/commands/github/cleanup.ts
src/index.ts
src/runner.ts
src/util.ts
src/utils/datasource/index.ts
src/utils/datasource/renovate-slim.ts
src/utils/docker.ts
src/utils/logger.ts
src/utils/renovate.ts
src/utils/versioning/index.ts
test/commands/docker/builder.spec.ts
test/commands/docker/config.spec.ts
test/commands/docker/publish.spec.ts
test/commands/github/cleanup.spec.ts
test/index.spec.ts
test/runner.spec.ts
test/setup.ts
test/util.spec.ts
test/utils/datasource/renovate-slim.spec.ts
test/utils/docker.spec.ts
test/utils/logger.spec.ts
test/utils/versioning/node.spec.ts
tsconfig.lint.json
yarn.lock

fix: wrong condition

---

src/util.ts
src/utils/docker.ts
src/utils/docker/common.ts
src/utils/types.ts
test/utils/__snapshots__/docker.spec.ts.snap
test/utils/docker.spec.ts

feat: retry build

---

src/commands/docker/builder.ts

This should fix latest full image build errors

fix: prune on error

---

src/utils/docker.ts
test/utils/docker.spec.ts

feat(docker): support v1 manifest

---

.github/workflows/build.yml
.releaserc
package.json
yarn.lock

chore(release): automatic semver releases

---

.github/workflows/build.yml
Dockerfile
e2e/helm.json
src/commands/docker/builder.ts
test/__snapshots__/util.spec.ts.snap

same as https://docs.renovatebot.com/configuration-options/#extractversion

feat(docker-builder): support extractVersion

---

.github/workflows/build.yml
e2e/node.json

Reverts renovatebot/internal-tools#203

Revert "chore(deps): pin node docker tag"

---

.github/workflows/build.yml
e2e/renovate.json

test: remove obsolete test

---

.github/workflows/build.yml
action.yml
package.json
src/commands/docker/builder.ts
src/utils/docker.ts
src/utils/docker/common.ts
src/utils/types.ts
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts
test/utils/docker.spec.ts

- Do not hardcore `renovate/` docker image prefix.
- Compile as es2020
- fix `action.yml` schema changes

feat: docker image prefix

---

package.json
yarn.lock

Reverts renovatebot/internal-tools#230

fix: Revert "fix(deps): update dependency @actions/github to v5"

---

src/utils/github.ts

The binary builder now loads all releaeses and caches them, so we heavily reduce API calls.
API limits are hit in `php-prebuild` repo.

feat: cache releases

---

src/utils/github.ts

Due to caching we don't got a new recently created releases.
So we now try to fetch existing release on failed creation validation.
Regression introduced in #238.
https://docs.github.com/en/rest/reference/repos#create-a-release

fix: race condition while creating release

---

.github/workflows/build.yml

see https://github.com/actions/setup-node/issues/281

ci: remove force color env

---

Dockerfile
src/commands/binary/index.ts
src/commands/docker/builder.ts
src/utils/config.ts
src/utils/types.ts
test/__snapshots__/util.spec.ts.snap
test/commands/docker/__fixtures__/helm.json
test/commands/docker/__snapshots__/builder.spec.ts.snap
test/commands/docker/builder.spec.ts

Support `lookupName` in `Dockerfile` regex and `builder.json`
- renovatebot/docker-helm#2

feat: support lookupName

---

.github/workflows/build.yml
action.yml
package.json
yarn.lock

See https://github.com/actions/runner/pull/1439

chore: target node16 runtime

---

.github/workflows/build.yml

ci: do not skip builds

---

.releaserc.json

chore(release):  no labels and comments

---

src/utils/builds.ts
src/utils/types.ts
test/utils/builds.spec.ts

support `allowedVersions` like in renovate

feat: support `allowedVersions`

---

.github/workflows/build.yml
package.json
src/commands/binary/index.ts
src/commands/docker/builder.ts
src/utils/builds.ts
test/commands/docker/builder.spec.ts

required to access github graphql api via renovate github-releases datasource

feat: add host rule if token is available

---

src/utils/cosign/common.ts
src/utils/docker.ts
test/utils/__snapshots__/docker.spec.ts.snap

fix(cosign): suppres input wait

---

package.json
src/utils/config.ts
yarn.lock

fixes possible regular expression injection

fix: escape input for regex

---

src/commands/binary/index.ts
src/utils/github.ts
test/commands/binary/index.spec.ts

- https://github.com/containerbase/base/issues/2849

feat(binary-builder): use latest stable version
